name: Auto Update Weather Data
on:
  schedule:
    # 每小时第1分钟运行一次（北京时间）
    - cron: '1 * * * *'
  workflow_dispatch: # 允许在GitHub页面上手动触发运行
  push:
    branches: [ main ] # 当main分支有推送时也运行（可选）

permissions:
  contents: write # 允许工作流向仓库提交文件

jobs:
  update-weather-data:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 2. 设置Python环境并安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: 3. 执行天气数据抓取脚本（每小时自动运行）
        run: |
          cat > fetch_weather.py << 'EOF'
          import requests
          from bs4 import BeautifulSoup
          from datetime import datetime, timezone, timedelta
          import csv
          import re

          # 配置
          TARGET_URL = "https://tianqi.moji.com/weather/china/sichuan/longquanyi-district"
          HEADERS = {
              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
              'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
              'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
              'Cache-Control': 'no-cache',
              'Referer': 'https://tianqi.moji.com/'
          }

          def get_beijing_time():
              """获取当前北京时间 (UTC+8)"""
              utc_now = datetime.now(timezone.utc)
              beijing_tz = timezone(timedelta(hours=8))
              beijing_now = utc_now.astimezone(beijing_tz)
              return beijing_now

          def fetch_weather_data():
              """抓取天气数据"""
              print(f"🌤️ 正在访问天气网站: {TARGET_URL}")
              try:
                  resp = requests.get(TARGET_URL, headers=HEADERS, timeout=30)
                  resp.raise_for_status()
                  resp.encoding = 'utf-8'
              except Exception as e:
                  print(f"❌ 网络请求失败: {e}")
                  return None

              soup = BeautifulSoup(resp.content, 'lxml')
              
              # 获取24小时预报数据
              hourly_forecast = []
              
              # 查找24小时预报区域
              forecast_sections = soup.find_all('div', class_=re.compile(r'forecast|hourly'))
              
              found_data = False
              
              for section in forecast_sections:
                  # 查找时间行和温度行
                  time_row = section.find('ul', class_=re.compile(r'time|hours'))
                  temp_row = section.find('ul', class_=re.compile(r'temp|temperature'))
                  
                  if time_row and temp_row:
                      # 提取时间
                      times = []
                      time_items = time_row.find_all('li')
                      for item in time_items:
                          time_text = item.get_text(strip=True)
                          if time_text and re.match(r'\d{1,2}:\d{2}', time_text):
                              times.append(time_text)
                      
                      # 提取温度
                      temps = []
                      temp_items = temp_row.find_all('li')
                      for item in temp_items:
                          temp_text = item.get_text(strip=True)
                          # 提取数字（可能包含℃符号）
                          temp_match = re.search(r'(-?\d+)℃?', temp_text)
                          if temp_match:
                              temps.append(f"{temp_match.group(1)}°C")
                          elif temp_text:
                              temps.append(temp_text)
                      
                      # 匹配时间和温度
                      for i in range(min(len(times), len(temps))):
                          hourly_forecast.append({
                              'forecast_time': times[i],
                              'temperature': temps[i]
                          })
                      
                      if hourly_forecast:
                          found_data = True
                          break
              
              # 如果没有找到标准格式的数据，尝试备用方案
              if not found_data:
                  print("⚠️  未找到标准24小时预报格式，尝试备用方案...")
                  
                  # 查找所有可能包含时间温度的元素
                  all_text = soup.get_text()
                  time_pattern = r'(\d{1,2}):(\d{2})\s*(-?\d+℃?|-?\d+°C?)'
                  matches = re.findall(time_pattern, all_text)
                  
                  for match in matches:
                      hour = match[0]
                      minute = match[1]
                      temp = match[2]
                      hourly_forecast.append({
                          'forecast_time': f"{hour}:{minute}",
                          'temperature': temp
                      })
                  
                  # 限制最多24条数据
                  hourly_forecast = hourly_forecast[:24]
              
              return hourly_forecast

          def save_latest_weather_data(forecast_data):
              """保存最新的天气数据到CSV文件（覆盖模式）"""
              beijing_time = get_beijing_time()
              update_time_str = beijing_time.strftime('%Y-%m-%d %H:%M:%S')
              
              csv_file = 'weather_forecast.csv'
              
              # 使用覆盖模式写入，只保留最新数据
              with open(csv_file, 'w', newline='', encoding='utf-8') as f:
                  writer = csv.writer(f)
                  
                  # 写入表头
                  writer.writerow(['update_time', 'forecast_time', 'temperature', 'data_source'])
                  
                  if forecast_data:
                      # 写入最新的24小时预报数据
                      for forecast in forecast_data:
                          writer.writerow([
                              update_time_str,
                              forecast['forecast_time'],
                              forecast['temperature'],
                              TARGET_URL
                          ])
                      print(f"✅ 已更新最新的 {len(forecast_data)} 小时天气预报数据")
                  else:
                      # 如果没有数据，写入一条空记录
                      writer.writerow([
                          update_time_str,
                          'N/A',
                          'N/A',
                          f'Error: 无法获取数据 | {TARGET_URL}'
                      ])
                      print("⚠️  未获取到天气数据，写入空记录")
              
              print(f"⏰ 数据更新时间（北京时间）: {update_time_str}")
              print(f"📁 文件模式: 覆盖更新 (每次只保留最新数据)")
              
              return update_time_str, len(forecast_data) if forecast_data else 0

          # 主程序入口
          if __name__ == "__main__":
              print("=" * 60)
              print("🌤️  24小时天气数据自动抓取任务开始")
              beijing_time = get_beijing_time()
              print(f"📅 当前北京时间: {beijing_time.strftime('%Y-%m-%d %H:%M:%S')}")
              print(f"📌 数据模式: 覆盖更新 (只保留最新数据)")
              print("=" * 60)
              
              forecast_data = fetch_weather_data()
              update_time, data_count = save_latest_weather_data(forecast_data)
              
              print("-" * 60)
              
              # 显示获取的数据
              if forecast_data:
                  print(f"📊 最新的 {data_count} 小时天气预报数据:")
                  for i, forecast in enumerate(forecast_data):
                      if i < 10:  # 只显示前10小时
                          print(f"  {forecast['forecast_time']}: {forecast['temperature']}")
                  if len(forecast_data) > 10:
                      print(f"  ... 还有 {len(forecast_data) - 10} 小时数据")
              else:
                  print("⚠️  未获取到天气预报数据")
              
              print("=" * 60)
              print(f"🎉 任务完成！最新数据已保存到 weather_forecast.csv")
              print("=" * 60)
          EOF
          
          echo "开始执行Python脚本..."
          python3 fetch_weather.py

      - name: 4. 查看生成的CSV文件
        run: |
          echo "=== 生成的文件列表 ==="
          ls -la *.csv 2>/dev/null || echo "未找到CSV文件"
          echo ""
          echo "=== CSV文件内容预览 ==="
          if [ -f "weather_forecast.csv" ]; then
            echo "文件大小:"
            ls -lh weather_forecast.csv
            echo ""
            echo "文件总行数:"
            wc -l weather_forecast.csv
            echo ""
            echo "文件内容预览 (前15行):"
            head -15 weather_forecast.csv
            echo ""
            echo "最新更新时间:"
            head -2 weather_forecast.csv | tail -1 | cut -d',' -f1
          else
            echo "weather_forecast.csv 文件不存在"
          fi

      - name: 5. 提交更新到仓库
        run: |
          # 配置Git用户
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 添加生成的CSV文件
          git add weather_forecast.csv 2>/dev/null || echo "注意：未找到CSV文件"
          
          # 检查是否有文件变更
          if git diff --staged --quiet; then
            echo "ℹ️  数据无变化，无需提交。"
          else
            # 提交并推送（使用北京时间时间戳）
            BEIJING_TIME=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
            # 获取数据数量用于提交信息
            DATA_COUNT=$(head -2 weather_forecast.csv 2>/dev/null | tail -1 | grep -c "N/A" || echo "0")
            if [ "$DATA_COUNT" = "0" ]; then
              RECORD_COUNT=$(( $(wc -l < weather_forecast.csv 2>/dev/null || echo 1) - 1 ))
              git commit -m "🌤️ 自动更新天气数据 [${BEIJING_TIME} 北京时间] - ${RECORD_COUNT}小时最新预报"
            else
              git commit -m "🌤️ 自动更新天气数据 [${BEIJING_TIME} 北京时间] - 数据抓取失败"
            fi
            git push
            echo "✅ 最新天气数据更新已提交并推送！"
          fi
